// <auto-generated />
using System;
using DevJobMatcher.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevJobMatcher.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DevJobMatcher.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CampanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Dev", b =>
                {
                    b.Property<int>("DevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("DevId");

                    b.ToTable("Devs");
                });

            modelBuilder.Entity("DevJobMatcher.Models.DevProfile", b =>
                {
                    b.Property<int>("DevProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DevId")
                        .HasColumnType("int");

                    b.HasKey("DevProfileId");

                    b.HasIndex("DevId");

                    b.ToTable("DevProfiles");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("JobId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DevJobMatcher.Models.JobSkill", b =>
                {
                    b.Property<int>("JobSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("JobSkillId");

                    b.HasIndex("JobId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DevProfileId")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("DevProfileId");

                    b.HasIndex("JobId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("DevJobMatcher.Models.SelectedSkill", b =>
                {
                    b.Property<int>("SelectedSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DevProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SelectedSkillId");

                    b.HasIndex("DevProfileId");

                    b.ToTable("SelectedSkills");
                });

            modelBuilder.Entity("DevJobMatcher.Models.DevProfile", b =>
                {
                    b.HasOne("DevJobMatcher.Models.Dev", "Creator")
                        .WithMany()
                        .HasForeignKey("DevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Job", b =>
                {
                    b.HasOne("DevJobMatcher.Models.Company", "Creator")
                        .WithMany("CreatedJobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DevJobMatcher.Models.JobSkill", b =>
                {
                    b.HasOne("DevJobMatcher.Models.Job", "SkillCreator")
                        .WithMany("SkillsNeeded")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillCreator");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Match", b =>
                {
                    b.HasOne("DevJobMatcher.Models.DevProfile", "DevProfileMatched")
                        .WithMany("MatchedProfiles")
                        .HasForeignKey("DevProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevJobMatcher.Models.Job", "JobMatched")
                        .WithMany("MatchedJobs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DevProfileMatched");

                    b.Navigation("JobMatched");
                });

            modelBuilder.Entity("DevJobMatcher.Models.SelectedSkill", b =>
                {
                    b.HasOne("DevJobMatcher.Models.DevProfile", "Creator")
                        .WithMany("SelectedSkills")
                        .HasForeignKey("DevProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Company", b =>
                {
                    b.Navigation("CreatedJobs");
                });

            modelBuilder.Entity("DevJobMatcher.Models.DevProfile", b =>
                {
                    b.Navigation("MatchedProfiles");

                    b.Navigation("SelectedSkills");
                });

            modelBuilder.Entity("DevJobMatcher.Models.Job", b =>
                {
                    b.Navigation("MatchedJobs");

                    b.Navigation("SkillsNeeded");
                });
#pragma warning restore 612, 618
        }
    }
}
